### ISSUE TITLE
lat lon with colors as the 5th argument are not parsed properly

### ISSUE THREAD

**Issue by ColaIan** [eirslett/sector-file-tools#16]
For example
```
VHHH/ATZ                N000.00.00.000 E000.00.00.000 N000.00.00.000 E000.00.00.000
		        N022.19.58.000 E113.51.11.000 N022.21.45.000 E113.56.58.000 ATZ
                        N022.21.45.000 E113.56.58.000 N022.17.05.000 E113.58.41.000 ATZ
                        N022.17.05.000 E113.58.41.000 N022.15.24.000 E113.53.00.000 ATZ
                        N022.15.24.000 E113.53.00.000 N022.19.58.000 E113.51.11.000 ATZ
```
results in `The input E113.51.11.000 is neither a latitude or registered navaid.` since the parsing method takes the last 4 parts as the start and end coordinates

Reference:
```js
const [startLat, startLon, endLat, endLon] = parts.slice(-4);
```

**Comment by eirslett** [comment]
You can submit a PR with a unit test and bug fix!

**Comment by ColaIan** [comment]
> You can submit a PR with a unit test and bug fix!

lol I probably should when I have time but can't tell when I have time for that yet, will do when it hasn't been fixed yet 🤣

**Comment by pierr3** [comment]
This seems to have been fixed as the code checks whether the last part is a longitude or not
